engine: add Close method for nopQueryTracker
Unblock Thanos Prometheus go.mod update by providing missing method:

```
../../go/pkg/mod/github.com/thanos-io/promql-engine@v0.0.0-20240718195911-cdbd6dfed36b/engine/engine.go:173:41: cannot use nopQueryTracker{} (value of type nopQueryTracker) as promql.QueryTracker value in variable declaration: nopQueryTracker does not implement promql.QueryTracker (missing method Close)
```

Signed-off-by: Giedrius Statkevičius <giedrius.statkevicius@vinted.com>